### ISSUE TITLE
HOw?

### ISSUE THREAD

**Issue by JimLynchCodes** [webrtc-rs/media#6]
How do I use this??

The README is such empty...

**Comment by rainliu** [comment]
currently media crate just provides minimal support for Audio/Video IO read/write for opus/vpx/h264. More functionalities are not ready yet.

**Comment by k0nserv** [comment]
We have migrated this crate to the monorepo([webrtc-rs/webrtc](https://github.com/webrtc-rs/webrtc/)) please re-open this issue over there.
