### ISSUE TITLE
Doc comments for `Sample` would be helpful

### ISSUE THREAD

**Issue by KallDrexx** [webrtc-rs/media#7]
It's not clear what some of the fields for the `Sample` type are.  

What is `timestamp`?  I would assume a `timestamp` field would be number of ms or ns from an undefined epoch (start of stream) but it's type is a `SystemTime`, which means it's tied to an absolute clock time. 

What is `duration` and why do the examples set it to a constant 1 second?  

Is `packet_timestamp` somehow adjusted (since the examples leave it at the default of 0)?

In essence, it's not clear to me what the proper mechanism is to set the dts and/or pts values for my media.

**Comment by k0nserv** [comment]
We have migrated this crate to the monorepo([webrtc-rs/webrtc](https://github.com/webrtc-rs/webrtc/)) please re-open this issue over there.
